name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'scala-steward'
    steps:
      - uses: hmarr/auto-approve-action@v3
