name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Code style
        run: sbt scalafmtCheckAll
      - name: Linting
        run: sbt "scalafixAll --check"
      - name: Tests
        run: sbt +test
      - name: Readme
        run: sbt docs/mdoc
